-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS subscriptions
    ( 
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        url text NOT NULL,
        filter text NOT NULL,
        content_type text NOT NULL,
        use_chrome boolean NOT NULL,
        PRIMARY KEY(id),
        UNIQUE(url, filter, content_type)
    );
CREATE TABLE IF NOT EXISTS subscribers
    (
        email text NOT NULL,
        subscription_limit int,
        PRIMARY KEY(email)
    );
CREATE TABLE IF NOT EXISTS subscriber_subscription
    (
        subscriber_email text NOT NULL,
        subscription_id bigint NOT NULL,
        interval interval NOT NULL,
        PRIMARY KEY(subscriber_email, subscription_id),
        FOREIGN KEY(subscriber_email) REFERENCES subscribers(email) ON UPDATE CASCADE ON DELETE CASCADE,
        FOREIGN KEY(subscription_id) REFERENCES subscriptions(id) ON UPDATE CASCADE ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS sites
    (
        url text NOT NULL,
        filter text NOT NULL,
        content_type text NOT NULL,
        last_updated time with time zone,
        last_checked time with time zone,
        content text NOT NULL,
        checksum text NOT NULL,
        diff text NOT NULL,
        PRIMARY KEY(url, filter, content_type)
    );
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS subscriber_subscriptions;
DROP TABLE IF EXISTS subscribers CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;
-- +goose StatementEnd
